version: 2.1
orbs:
  # Your orb will be automatically injected here during the pipeline.
  # Reference your orb's jobs and commands below as they will exist when built.
  orb-tools: circleci/orb-tools@12.0
  # The orb definition is intentionally not included here. It will be injected into the pipeline.
  node-ecs: {}

# Use this tag to ensure test jobs always run,
# even though the downstream publish job will only run on release tags.
filters: &filters
  tags:
    only: /.*/

# Filter for release tags.
release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  test-terraform_plan:
    executor: node-ecs/node20
    resource_class: small
    steps:
      - checkout
      - node-ecs/terraform_plan:
          aws_account_id: "880892332156"
          db_tunnel_mapping: "5432:main_database_host"
          dir: test
          env: development
          service_name: "circle-ci-terraform-orb"
          ssh_key_fingerprint: "82:27:10:3f:4c:a3:c5:8c:7e:6a:f3:a3:b6:dc:1e:79"

  test-terraform_validate:
    executor: node-ecs/node20
    resource_class: small
    steps:
      - checkout
      - node-ecs/terraform_validate:
          aws_account_id: "880892332156"
          dir: test
          env: development
          service_name: "circle-ci-terraform-orb"

  test-terraform_deploy:
    executor: node-ecs/node20
    resource_class: small
    steps:
      - checkout
      - node-ecs/terraform_deploy:
          aws_account_id: "880892332156"
          db_tunnel_mapping: "5432:main_database_host"
          dir: test
          env: development
          service_name: "circle-ci-terraform-orb"
          ssh_key_fingerprint: "82:27:10:3f:4c:a3:c5:8c:7e:6a:f3:a3:b6:dc:1e:79"

workflows:
  test-deploy:
    jobs:
      - test-terraform_validate:
          context: node
          filters: *filters
      - test-terraform_plan:
          context: node
          requires:
            - test-terraform_validate
          filters: *filters
      - test-terraform_deploy:
          context: node
          requires:
            - test-terraform_plan
          filters: *filters
      # The orb must be re-packed for publishing, and saved to the workspace.
      - orb-tools/pack:
          filters: *release-filters
      - orb-tools/publish:
          orb_name: figure/node-ecs
          vcs_type: << pipeline.project.type >>
          pub_type: production
          # Ensure this job requires all test jobs and the pack job.
          requires:
            - orb-tools/pack
            - test-terraform_plan
            - test-terraform_validate
            - test-terraform_deploy
          context: orb-publishing
          filters: *release-filters
