description: >
  generate pipeline config according to changed folders

parameters:
  pipeline_parameters_json_file:
    type: string
    default: /tmp/pipeline-parameters.json

steps:
  - run:
      name: Generate configuration
      environment:
        CONFIG_JSON_FILE: << parameters.pipeline_parameters_json_file >>
      command: << include(scripts/generate-config.sh) >>
