parameters:
  db_tunnel_mapping:
    type: string
    default: ""
    description: "Mapping of ports to hostnames stored in SSM in format: port:ssm_param,port:ssm_param"
  service_name:
    type: string
    default: "service"
  ssh_key_fingerprint:
    type: string
    default: ""
    description: "SSH Key Fingerprint"

jobs:
  terraform_plan_dev:
    description: "Terraform Plan for Development"
    executor: node-ecs/node20
    steps:
      - checkout
      - node-ecs/terraform_plan:
          account_id: "880892332156"
          db_tunnel_mapping: <<pipeline.parameters.db_tunnel_mapping>>
          env: development
          service_name: <<pipeline.parameters.service_name>>
          ssh_key_fingerprint: <<pipeline.parameters.ssh_key_fingerprint>>
      - node-ecs/slack_notify_fail_master:
          service_name: <<pipeline.parameters.service_name>>

  terraform_validate:
    description: "Terraform Validation"
    executor: node-ecs/node20
    steps:
      - checkout
      - node-ecs/terraform_validate:
          account_id: "880892332156"
          env: development
          service_name: <<pipeline.parameters.service_name>>
          ssh_key_fingerprint: <<pipeline.parameters.ssh_key_fingerprint>>
      - node-ecs/slack_notify_fail_master:
          service_name: <<pipeline.parameters.service_name>>

  terraform_deploy_dev:
    description: "Terraform Deployment to Development"
    executor: node-ecs/node20
    steps:
      - checkout
      - node-ecs/terraform_deploy:
          account_id: "880892332156"
          db_tunnel_mapping: <<pipeline.parameters.db_tunnel_mapping>>
          env: development
          service_name: <<pipeline.parameters.service_name>>
          ssh_key_fingerprint: <<pipeline.parameters.ssh_key_fingerprint>>
      - node-ecs/slack_notify_fail_master:
          service_name: <<pipeline.parameters.service_name>>

  terraform_plan_prod:
    description: "Terraform Plan for Production"
    executor: node-ecs/node20
    steps:
      - checkout
      - node-ecs/terraform_plan:
          account_id: "682919404744"
          db_tunnel_mapping: <<pipeline.parameters.db_tunnel_mapping>>
          env: production
          service_name: <<pipeline.parameters.service_name>>
          ssh_key_fingerprint: <<pipeline.parameters.ssh_key_fingerprint>>
      - node-ecs/slack_notify_fail_master:
          service_name: <<pipeline.parameters.service_name>>

  terraform_deploy_prod:
    description: "Terraform Deployment to Production"
    executor: node-ecs/node20
    steps:
      - checkout
      - node-ecs/terraform_deploy:
          account_id: "682919404744"
          db_tunnel_mapping: <<pipeline.parameters.db_tunnel_mapping>>
          env: production
          service_name: <<pipeline.parameters.service_name>>
          ssh_key_fingerprint: <<pipeline.parameters.ssh_key_fingerprint>>
      - node-ecs/slack_notify_fail_master:
          service_name: <<pipeline.parameters.service_name>>
