version: 2.1

orbs:
  node: circleci/node@5.1.0
  node-ecs: figure/node-ecs@1.6.5

parameters:
  service_name:
    type: string
    default: "service"

workflows:
  terraform_validation_deploy:
    jobs:
      - terraform_plan_dev:
          context:
            - node
      - terraform_validate:
          context:
            - node
          requires:
            - terraform_plan_dev
      - terraform_deploy_dev:
          context:
            - node
          requires:
            - terraform_validate
          filters:
            branches:
              only: master
      - terraform_plan_prod:
          context:
            - node
      - terraform_assess_plan_changed_prod:
          context:
            - node
          requires:
            - terraform_validate
            - terraform_plan_prod
          filters:
            branches:
              only: master
      - approve_terraform_deploy_prod:
          type: approval
          requires:
            - terraform_assess_plan_changed_prod
          filters:
            branches:
              only: master
      - terraform_deploy_prod:
          context:
            - node
          requires:
            - approve_terraform_deploy_prod
          filters:
            branches:
              only: master


jobs:
  terraform_plan_dev:
    description: "Terraform Plan for Development"
    executor: node-ecs/node20
    steps:
      - checkout
      - node-ecs/terraform_plan:
          account_id: "880892332156"
          env: development
      - node-ecs/slack_notify_fail_master:
          service_name: << pipeline.parameters.service_name >>

  terraform_validate:
    description: "Terraform Validation"
    executor: node-ecs/node20
    steps:
      - checkout
      - node-ecs/terraform_validate:
          account_id: "880892332156"
      - node-ecs/slack_notify_fail_master:
          service_name: << pipeline.parameters.service_name >>

  terraform_deploy_dev:
    description: "Terraform Deployment to Development"
    executor: node-ecs/node20
    steps:
      - checkout
      - node-ecs/terraform_deploy:
          account_id: "880892332156"
          env: development
      - node-ecs/slack_notify_fail_master:
          service_name: << pipeline.parameters.service_name >>

  terraform_assess_plan_changed_prod:
    description: "Assess if the Plan for Production Changed"
    executor: node-ecs/node20
    steps:
      - checkout
      - node-ecs/terraform_assess_plan_changed:
          env: production
      - node-ecs/slack_notify_fail_master:
          service_name: << pipeline.parameters.service_name >>

  terraform_plan_prod:
    description: "Terraform Plan for Production"
    executor: node-ecs/node20
    steps:
      - checkout
      - node-ecs/terraform_plan:
          account_id: "682919404744"
          env: production
      - node-ecs/slack_notify_fail_master:
          service_name: << pipeline.parameters.service_name >>

  terraform_deploy_prod:
    description: "Terraform Deployment to Production"
    executor: node-ecs/node20
    steps:
      - checkout
      - node-ecs/terraform_deploy:
          account_id: "682919404744"
          env: production
      - node-ecs/slack_notify_fail_master:
          service_name: << pipeline.parameters.service_name >>
